import Login from "./Login";
import Register from "./Register";
import HomePage from "./Home";
import Header from "./Header";
import GetStarted from "./GetStarted";
import AuthLayout from "./AuthLayout";
import BoardsSection from "./Boards";
import SideBar from "./SideBar";
import BoardsComponents from "./Card";
export {Login,Register,HomePage,Header,GetStarted,AuthLayout,BoardsSection,SideBar,BoardsComponents};
